import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>

      <Script
        id="convolo-widget" // Unique ID for the script
        strategy="afterInteractive" // Load after page becomes interactive
        dangerouslySetInnerHTML={{
          __html: `
            (function f() {
              var widget_key = '90cd24adf617226f9fb6fe512569135d';
              window.leadCM = { widget_key: widget_key };
              var em = document.createElement('script');
              em.type = 'text/javascript';
              em.async = true;
              em.src = 'https://app.convolo.ai/js/icallback.js?v=' + Math.random() + '&key=' + widget_key + '&uri=' + encodeURIComponent(window.location.href);
              var s = document.getElementsByTagName('script')[0];
              s.parentNode.insertBefore(em, s);
            })();
          `,
        }}
      />
    </html>
  );
}
